.TH BPSYNC "1" "February 2013" "mygpoclient 1.7" "User Commands"
.SH NAME
mygpo-bpsync \- Synchronize BashPodder subscriptions with gpodder.net
.SH SYNOPSIS
.B mygpo-bpsync
(\fIput|get\fR)
[\fIdevice-id\fR]

.SH DESCRIPTION
.PP
bpsync is a simple gpodder.net client application for syncing a BashPodder
(\fIhttp://lincgeek.org/bashpodder/\fR) subscription list from and to the
web service. As BashPodder uses a simple one-URL-per-line subscription list
format, this script can be used with other applications, too (or to simply
backup gpodder.net subscription URLs as plain text file).

.PP
If you have added a subscription on gpodder.net, you can use the \fBget\fR
sub-command to overwrite the local subscription list with the list stored
on gpodder.net. If you have added a subscription locally, you can use the
\fBput\fR sub-command to overwrite the list on gpodder.net with the list
stored in the BashPodder subscription list.

.SH ENVIRONMENT VARIABLES

.PP
The following environment variables must be set for
.B mygpo-bpsync
to work:

.PP
.B MYGPO_USERNAME
.RS 4
Username for the web service
.RE

.PP
.B MYGPO_PASSWORD
.RS 4
Password for the web service
.RE

.PP
The following environment variables are optional:

.PP
.B BPSYNC_BP_CONF
.RS 4
Path to your bp.conf file (default: \fIbp.conf\fR)
.RE

.PP
.B MYGPO_HOSTNAME
.RS 4
Host or URL of the webservice to use (default: \fIhttp://gpodder.net\fR)
.RE

.SH EXAMPLES

.PP
.B mygpo-bpsync put
.RS 4
Upload bp.conf as device "bp"
.RE

.PP
.B mygpo-bpsync get
.RS 4
Download subscriptions for device "bp"
.RE

.PP
.B mygpo-bpsync get mydev
.RS 4
Download subscriptions for device "mydev"
.RE

.SH SEE ALSO
.PP
gpodder(1)

.SH REPORTING BUGS
.PP
\fIhttps://bugs.gpodder.org/enter_bug.cgi?product=mygpoclient\fR

.SH WEBSITE
.PP
\fIhttp://thp.io/2010/mygpoclient/\fR
